%option noyywrap
%{
#include <boost/lexical_cast.hpp>
#include "yyglobal.hpp"
#include "parser.hpp"

%}

DIGIT [0-9]
ID [a-zA-Z][a-zA-Z0-9]*

%%

{DIGIT}+ { yylval = boost::lexical_cast<int>(yytext); return NUMBER; }

{ID} { yylval = string(yytext); /*std::cout<<get<string>(yylval)<<std::endl;*/return IDENTIFY; }

"*" { return '*'; }
"+" { return '+'; }
"-" { return '-'; }
"=" { return '='; }
"^" { return '^'; }

[ \t\n]+

%%
